defaultContentLanguage = "en"
title = "Eclipse RDF4J"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
baseURL = "http://example.org/"
languageCode = "en-us"
themesdir = "node_modules/"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
  logo = "assets/images/rdf4j-logo-114.png"
  google_tag_manager = ""
  description = "Eclipse RDF4J: "
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | Scalable RDF for Java developers"
  keywords = ["rdf", "sparql", "sesame", "owl", "ontology", "linked data", "turtle"]

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

