defaultContentLanguage = "en"
title = "Eclipse Rdf4j"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
baseURL = "http://example.org/"
languageCode = "en-us"
themesdir = "node_modules/"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
  logo = "assets/images/rdf4j-logo-114.png"
  google_tag_manager = ""
  description = "Eclipse Rdf4j: "
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | Scalable RDF for Java developers"
  keywords = ["rdf", "sparql", "ontology", "linked data", "turtle"]

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
weight = 2
